[database]
host = "localhost"
ports = 3306
user = "root"
password = "1"
db_name ="merchant"

[rabbit]
host = "localhost"
ports = 32776
user = "guest"
password = "guest"

[producer]
exchange_name = "goProcessing"
instance_count = 2

[collectors]
[collectors.cancel]
handler = "Cancel"
repeat_period = 1
sql_query_file="./config/sql/cancelByUserRequest.sql"
[collectors.cancel.params]
reason = "requestFromUser"

[collectors.run]
handler = "Run"
repeat_period = 1
sql_query_file="./config/sql/cancelByUserRequest.sql"
[collectors.run.params]
reason = "requestFromUser"
description = "some text"

[collectors.notify]
handler = "Notify"
repeat_period = 1
sql_query_file="./config/sql/cancelByUserRequest.sql"
[collectors.notify.params]
reason = "requestFromUser"